/**
 * @file Mesh.hpp
 * @author Andrés Ragot (github.com/andresragot)
 * @brief This file implements the Mesh class, which represents a 3D mesh in the Ragot engine.
 * @details The Mesh class is a base class for creating 3D meshes with vertices and faces.
 * It provides methods to generate vertices and faces, apply transformations, and manage mesh information.
 * The class also includes methods for setting and getting the color of the mesh.
 * @version 1.0
 * @date 2025-06-01
 * 
 * @copyright Copyright (c) 2025
 * MIT License
 * 
 * Copyright (c) 2025 Andrés Ragot 
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#pragma once

#include "CommonTypes.hpp"
#include "Camera.hpp"
#include <vector>
#include <cmath>
#include "Components.hpp"
#include <glm.hpp>

namespace Ragot
{
    /**
     * @class Mesh
     * @brief Represents a 3D mesh in the Ragot engine.
     * 
     * The Mesh class is a base class for creating 3D meshes with vertices and faces.
     * It provides methods to generate vertices and faces, apply transformations, and manage mesh information.
     * The class also includes methods for setting and getting the color of the mesh.
     */
    class Mesh : public Component
    {
    protected:
        
        mesh_info_t mesh_info; ///< Information about the mesh, including coordinates and rendering type.
        uint16_t color = 0xFFFF; ///< Color of the mesh, default is white (0xFFFF).
        
        std::vector < glm::fvec4 > vertices; ///< Vector of vertices representing the mesh in 3D space.
        std::vector <   face_t > faces; ///< Vector of faces representing the mesh, each face can be a triangle or a quad.
        
        int slices = 16; ///< Number of slices for generating the mesh, default is 16.

        // Bounding sphere in the same space as `vertices` (usually world space
        // after apply_transform_to_vertices). Computed lazily on first request
        // or whenever recalculate() runs.
        mutable glm::vec3 bounding_center { 0.f };
        mutable float     bounding_radius = -1.f; ///< <0 means "not computed yet".
        
    public:
        /**
         * @brief Construct a new Mesh object (deleted constructor).
         */
        Mesh() = delete;

        /**
         * @brief Default virtual destructor for the Mesh class.
         * 
         * Cleans up the mesh and its resources.
         */
        virtual ~Mesh() = default;
       
        /**
         * @brief Construct a new Mesh object with mesh information.
         * 
         * Initializes the mesh with the provided mesh information.
         * 
         * @param mesh_info Information about the mesh, including coordinates and rendering type.
         */
        Mesh(mesh_info_t & mesh_info);
        
        /**
         * @brief Generate vertices for the mesh.
         * 
         * This method is pure virtual and must be implemented by derived classes.
         * It is responsible for generating the vertices of the mesh based on the mesh information.
         */
        virtual void generate_vertices() = 0;

        /**
         * @brief Generate faces for the mesh.
         * 
         * This method is pure virtual and must be implemented by derived classes.
         * It is responsible for generating the faces of the mesh based on the vertices generated by generate_vertices.
         */
        virtual void generate_faces() = 0;
        
        /**
         * @brief Get the vertices object
         * 
         * @return const std::vector < glm::fvec4 >& 
         */
        const std::vector < glm::fvec4 > & get_vertices() const { return vertices; }

        /**
         * @brief Get the faces object
         * 
         * @return const std::vector < face_t >& 
         */
        const std::vector <   face_t > & get_faces()    const { return faces;    }


        /**
         * @brief Get the total vertices object
         * 
         * @return const size_t 
         */
        size_t get_total_vertices() const { return vertices.size(); }

        /**
         * @brief Get the total vertices object
         * 
         * @return size_t 
         */
        size_t get_total_vertices()       { return vertices.size(); }

        /**
         * @brief Recalculate the mesh vertices and faces.
         */
        void recalculate()
        {
            vertices.clear();
            faces.clear();
            
            generate_vertices();
            generate_faces();
            
            apply_transform_to_vertices();
            invalidate_bounding_sphere();
        }
        
        /**
         * @brief Apply the current transformation to the vertices of the mesh.
         * This method applies the transformation matrix obtained from the Transform class to each vertex in the mesh.
         * This is useful for updating the mesh vertices after any transformation has been applied, such as translation, rotation, or scaling.
         * It modifies the vertices in place, transforming them according to the current transformation matrix.
         */
        void apply_transform_to_vertices()
        {
            glm::mat4 M = get_transform_matrix();
            for (auto & v : vertices)
            {
                v = M * v;
            }
            invalidate_bounding_sphere();
        }

        /**
         * @brief Marks the cached bounding sphere as dirty so it is recomputed
         * the next time it is requested.
         */
        void invalidate_bounding_sphere() const { bounding_radius = -1.f; }

        /**
         * @brief Returns the bounding sphere center (in the same space as
         * `vertices`). Computed lazily on first request.
         */
        const glm::vec3 & get_bounding_center() const
        {
            ensure_bounding_sphere();
            return bounding_center;
        }

        /**
         * @brief Returns the bounding sphere radius (in the same space as
         * `vertices`). Computed lazily on first request.
         */
        float get_bounding_radius() const
        {
            ensure_bounding_sphere();
            return bounding_radius;
        }

    private:
        void ensure_bounding_sphere() const
        {
            if (bounding_radius >= 0.f) return;
            if (vertices.empty())
            {
                bounding_center = glm::vec3(0.f);
                bounding_radius = 0.f;
                return;
            }
            glm::vec3 c(0.f);
            for (auto & v : vertices) c += glm::vec3(v);
            c /= float(vertices.size());
            float r2 = 0.f;
            for (auto & v : vertices)
            {
                glm::vec3 d = glm::vec3(v) - c;
                float l2 = d.x * d.x + d.y * d.y + d.z * d.z;
                if (l2 > r2) r2 = l2;
            }
            bounding_center = c;
            bounding_radius = std::sqrt(r2);
        }

    public:

        /**
         * @brief Set the color of the mesh.
         * 
         * This method sets the color of the mesh to the specified new color.
         * 
         * @param new_color The new color to set for the mesh.
         */
        void set_color(uint16_t new_color)
        {
            color = new_color;
        }

        /**
         * @brief Get the color of the mesh.
         * 
         * This method returns the current color of the mesh.
         * 
         * @return uint16_t The color of the mesh.
         */
        uint16_t get_color() const
        {
            return color;
        }
    };
}
